name: build-and-deploy-docker-image

# Run workflow on push to main or manual trigger
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vocabversus-wordset-evaluator.tests
    steps:
        # checkout repository to runner
      - name: checkout repository
        uses: actions/checkout@v3
        
        # add the dotnet SDK
      - name: setup dotnet test environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

        # run all tests, this will also implicitely run dotnet restore and build
      - name: run tests
        run: dotnet test --verbosity normal
  build:
    runs-on: ubuntu-latest
    needs: test
    steps: 
        # checkout repository to runner
      - name: checkout repository
        uses: actions/checkout@v3

        # Setup docker hub credentials
      - name: authenticate docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Setup extended docker CLI with buildx plugin
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

        # Build docker image and push it to docker hub repository
      - name: build and push docker image to docker hub repository
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vocabversus-wordset-evaluator:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
        # Deploy docker hub image to azure with publish auth
      - name: deploy to azure
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'vocabversus-wordset-evaluator'
            publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISHPROFILE }}
            images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/vocabversus-wordset-evaluator:${{ github.sha }}'