name: build-docker-image

# Run workflow on push to main or manual trigger
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        # Get git functionality
      - name: checkout
        uses: actions/checkout@v3
        # Setup docker hub credentials
      - name: docker-hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Setup extended docker CLI with buildx plugin
      - name: docker-buildx
        uses: docker/setup-buildx-action@v2
        # build docker image and push it to docker hub repository
      - name: build docker image to docker hub repository
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vocabversus-wordset-evaluator:latest